server/rpc/game/game.coffee

Psychic created by WolfDiviner show first psychic result as “null#{@name}の霊能の結果、前日処刑された#{x.name}は#{x.psychicResult}でした。\n”, because @flag is null at that point.

WolfDiviner bug fix

---

server/prizedata.coffee

```.isCmplType()``` called at line 299 always gets the return value of ```false``` from ```class Player```.
And ```.isCmplType()``` is not defined in ```class Complex```
However, we don't really need ```chkCmplType()```, ```.isFriend()``` is enough.

lovers' prize counting bug fix

---

server/rpc/game/game.coffee

Pyrotechnist should break the blockade of Threatened.sunset, as Pyrotechnist's skill is one used during daytime and "Skill used by threatened player this night will be invalidated."(http://jinrou-doc.uhyohyo.net/jobs/ThreateningWolf.html)
Or rarely, if Pyrotechnist lit the fireworks AND got threatened by ThreateningWolf during one same daytime, this will cause conflicts:
1. Pyrotechnist's skill still works at this night (because #31 ), but nobody would get the tip of "The Pyrotechnist lit the fireworks, nobody can use skill tonight." (because ```Threatened.sunset```).
2. Pyrotechnist's skill will be active for two night, because he cannot ```@setFlag "done"``` at the first sunset.

Conflict fix

---

server/prize.coffee

Missing one ```else``` leads to a Great Extinction of prize.counterprize.

deal with the Great Extinction of prize.counterprize

---

server/rpc/game/game.coffee

1. gather ```midnightSort``` from all jobs
2. sort list of midnightSort, and make sure every element is unique.
3. apply ```pl.midnight(game,midnightSort)```,if ```@midnightSort``` is not equal to ```midnightSort```, this job would be skipped.

midnightSort bug fix

---

server/rpc/game/game.coffee

More missing midnightSort in 6adf92f . BombTrapped & TrapGuarded ask @midnightSort and class Complex did not define it, which makes BombTrapped & TrapGuarded working abnormally, TrapGuarded will kill both Guard and Werewolf as ```@midnightSort``` is undefined

BombTrapped & TrapGuarded need a @midnightSort

---

server/rpc/game/game.coffee

didn't refresh ```p```, which may lead to sudden death as ```p.sunset()``` is method of OLD p.

WolfDiviner bug

---

server/rpc/game/game.coffee

These ```.midnight()```, ```.job()``` and ```.sunrise()``` are not necessary, and the ```super``` in them would make TinyFox always ```@dodivine()``` for twice.
Success rate becomes 75% because of that.
[また、占い能力がありますが、50%の確率で失敗します（結果が得られません）。](http://jinrou-doc.uhyohyo.net/jobs/TinyFox.html)

TinyFox bug

---

server/rpc/game/game.coffee

Because ```.getTeam()``` didn't return their own @team.

BUG: FrankensteinsMonster eat Friends

---

server/rpc/game/rooms.coffee

This afternoon my server crashed, I'm almost sure that it is related to a player who pasted a 16KB base64 link for icon in blind room. How large could a session be?
```Forever``` tried to restart the server, but it always failed until I manually removed the suspected room from ```Mongo```. 
This is err.log [err_log.txt](https://github.com/uhyo/jinrou/files/824153/err_log.txt)
This is the [base64icon.txt](https://github.com/uhyo/jinrou/files/824174/base64icon.txt)
Yet, I failed to reproduce this crash again after my server back to normal.

BAN base64 icon

---

.gitignore
server/rpc/game/game.coffee

temporary treatment
should avoid using ```.accessByJobType()``` in calling method, as ```.accessByJobType("Pyrotechnist").sunset()``` works NOT the same between ```class Pyrotechnist``` and ```class PumpkinCostumed {main: class Pyrotechnist}```

avoid duplicate call of Pyrotechnist.sunset()

---

client/code/app/util.coffee
client/code/pages/game/game.coffee
client/templates/util/punish.jade
config.default/app.coffee
server/libs/blacklist.coffee
server/rpc/game/game.coffee
server/rpc/game/rooms.coffee

A Sudden Dead Player will be blocked for, at most, like 6 hours. Or will not be punished when forgave by all other player.
Perhaps it is a better idea to allow room owners to shorten this uplimit?
for #86

Sudden Death Punish

---

server/rpc/game/game.coffee

A ThreateningWolf scapegoat as last wolf will always sudden dead, because the ```super``` at last line of ```ThreateningWolf.sunset()``` is unreachable in such situation.
I roughly checked all the other ```/(?<!->\n\s+)super/```, and did not find more of the same problem.

ThreateningWolf scapegoat sudden dead bug

---

client/code/shared/game.coffee
server/rpc/game/game.coffee

This will describe this option more clearly.
And according to [this line](https://github.com/uhyo/jinrou/blob/8ad0edad6f1c7c5d246bc078d2a923c5b0d48510/server/rpc/game/game.coffee#L626) , Scapegoat is impossible to become a Werewolf by selecting ```no``` [here](https://github.com/uhyo/jinrou/blob/8ad0edad6f1c7c5d246bc078d2a923c5b0d48510/client/code/shared/game.coffee#L1356)

身代わりセーフティ description update

---

server/rpc/game/game.coffee

This may seem strange, but it did happen in [this room](https://www.werewolf.com.cn/room/65325) on player "Camus".
```Server.game.game.endlessCanEnter()``` failed to stop the second entering.
I am still not sure, but I suspect this is related to following bug.
> おかしいときは
> この人狼は基本的に手動の更新は不要ですが、タイミングの関係で動作がおかしくなる場合があります。たとえば他の人の発言が2重に表示されたり、時間が0になっても画面が切り替わらないときは、ブラウザの更新ボタンを押すかF5キーを押すなどしてページを更新するとだいたい直ります。
In one page, the client somehow subscribe same channel for twice, and ```room.join()``` got triggered for twice.

somehow players could join Game.participants twice in EndlessYaminabe

---

server/rpc/game/game.coffee

In [this room](https://www.werewolf.com.cn/room/66062), player 相对的正义 set himself as norevive while he was still ```class Watching``` at the 2nd night, however his ```@norevive``` was missing after he had joined as ```class Priest```.

@norevive should be transferred to newpl

---

client/code/pages/game/game.coffee

In [this line](https://github.com/uhyo/jinrou/blob/7c360d65ae17416a897470a9a36a7e9558761aae/front/src/game-view/players/box.tsx#L30), we should use `pl.realid` instead of `pl.id` if it's available.

uncover pl.realid when it's available

---

client/code/pages/game/game.coffee
front/src/game-view/defs.ts
front/src/game-view/players/box.tsx

The filter for highlighting player's comment relies on `PlayerInfo.id`.
[This line](https://github.com/uhyo/jinrou/blob/67928a24edcc0c292bc49cdfb6b258c0aa0891c6/client/code/pages/game/game.coffee#L747) makes it unable to highlight a certain player's comments after a room, which is ```room.rules.blind="yes"```, ended.

add realid instead of replacing id into realid

---

server/rpc/game/game.coffee

Without this ```scapegoatRunJobs()``` , game may stop at the end of ```Phase.night_remain```

add one scapegoatRunJobs()

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/140853
7日目夜に死亡者が警備員に任命されている。
エンドレス闇鍋しか想定していませんが、死亡者を除外。
転生すると警備員が消えるはずなので、生存者限定に。
プレイヤー人数から警備員を割り出すのではなく、生存人数から割り出したほうが良いかもしれません。→生存人数から割り出すように変更

警備員候補から死亡者を除外

---

server/rpc/game/game.coffee

https://twitter.com/hakoniwawind/status/1091347417918652417
出典元を調べていたら、霊能結果も人狼判定だったため。
占い結果は村人を人狼と判定してしまうことが多々あるが、霊能だけは正確（悪魔くんや犬といった例外はあるが…）というイメージを勝手に持っているのでどっちでもいいかなあという気持ちはあります。
月下人狼は出典元に従うイメージも強いですが。

Psychic result of Cosplayer is "werewolf"

---

client/code/shared/game.coffee

配役情報が、人狼系、妖狐系、狂人系の並びになっているのが気になるので、以下のように並び替えしています。
村人系、人狼系、狂人系、妖狐系、背徳系、恋人系、単独陣営、純正その他、変化系、村人系（変化）

Sort by teams

---

language/ja/roles.yaml

今まで勘違いしていたんですが、嘘つきは死人に対して霊能結果を返しているかと思っていました。
…ということで紛らわしいので、「霊能占い」から「霊能」を削除希望です。
ついでに、役職名を統一させたく、予言者のママの能力発動時に「占い師のママ」→「予言者のママ」に改訂。

Liar returns only fortune result! & 予言者のママ

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/142967
生存11に対して狼カウント4で試合が終わっている
https://jinrou.uhyohyo.net/room/142993 でも再現
人外系はishuman:->falseとしているため、
https://github.com/uhyo/jinrou/blob/445bbb1da83ec034501a225d542517e926c442f4/server/rpc/game/game.coffee#L3002-L3004
↑より、PhantomStolenは人間カウントが0になってしまっていると推測。
そこで、PhantomStolenはishumanをtrueにしました。
間違っていたらすみません。。

盗まれた人は人間カウントを持つ

---

server/rpc/game/game.coffee

身代わりくんがコピーだった場合、人外（悪魔くん含む）をコピーする確率を減らす。
（身代わりセーフティあり役職が冷遇処理を取っているため、こちらも同様に。）

身代わりくんがコピーの場合、人外も冷遇処理をする

---

server/rpc/game/game.coffee

セーフティ高以上で出現と宣言はしているが、
人狼1確定以外何も制約を受けないセーフティなしでも配役して良い気がします。

闇鍋セーフティなしで血まみれのメアリーを出現させる

---

language/ja/roles.yaml
server/rpc/game/game.coffee

人狼NETではサトリも初日白通知設定に影響されるため。
聞いた話では、牢獄の悪夢のパパラッチは影響されない様子。
呪殺判定持ち、強制系能力ならば適用したほうが良いと思ったので投げます。
sunsetを占い師から使いまわし。
ただし、サトリは大狼と占い師も除外しています。

サトリを初日白通知ありに適用する

---

server/rpc/game/game.coffee

ケミカル人狼で、チョコを食べてもストーカー変化しないように調整。
・背景
#501 ( dd3472f )
↑この修正により、ケミカル人狼においてパティシエールのチョコを食べてストーカーに変化した際、
従来はストーカー単独であったが、（恐らく）メイン役職のみがストーカーになる。
そうした場合、ケミカル人狼の勝利条件から、右側の役職陣営でも勝利が可能なため、
パティシエールの告発が容易になってしまう。
・対策
https://twitter.com/uhyo_/status/1101790069441028096

チョコを食べてもストーカーに変化はしない in Chemical

---

server/rpc/game/game.coffee

勝利がほぼ約束されているこの役職は悪く言えばゲームをぶち壊すのに躊躇いもなく、
少々厄介な存在なので、隠し役職として（都合の良い言い訳だが、）出現確率を減らしたく。
獅子舞みたいに大幅ダウンではなく、出現率は今までの6割～7割想定で考えています。
文句も少なからず出そうですが、如何でしょうか。

ニートの配役される確率を絞る

---

client/code/shared/game.coffee

色情報以外でも陣営数計算にjobinfoを使用しているみたいなので、 #568 が直るかと
取り急ぎ歌人の色は俳句の背景色と同じにしていますが、拘りなどあれば修正案をお願いします。

add Poet in jobinfo

---

server/rpc/game/game.coffee

①狂人狼は人気がない
　常に告発ゲームとなってしまうため。
②敗北村でニートを除外
　ほぼほぼ敗北となってしまう上に通常のプレイでは除外もできないため。

特定の役職を除外する

---

server/rpc/game/game.coffee

爆弾などの反撃で孤独な狼が対象になる事例がありました。
https://jinrou.uhyohyo.net/room/152062
確かにランダムで死亡するのですが、襲撃していない孤独な狼まで含まれるのはどうなのか？という話です。
爆弾魔はランダムではなく襲撃先が死にますが、恐らく身代わりくん襲撃がランダムだったから死亡したと思われます。
本Pullreqでは、身代わりくんの襲撃元、埋毒者猫又罠師のランダム死対象から孤独な狼を除外しています。

反撃のランダム死で孤独な狼は対象外にする

---

server/rpc/game/game.coffee

仕様変更：
人身御供が死亡時にも、能力が発動して守られる。
⇒人身御供が生存していないと能力が発動せずに死亡する。
理由は単純に、生贄以外の理由で既に死亡しているのに対し、人身御供をささげて守るのが違和感あるため…。

人身御供が生存していないと守られない

---

server/rpc/game/game.coffee

暴徒、狂愛者は絶対狼を選択することによって有利になると考えます。
厳密に言えば陣営変化ではないものの、暴動者や狂愛された場合も絶対的な力を剥奪する仕様変更です。
暴動者は警備員によって取り除けますので、そこら辺で夜襲撃役職と被った場合ちょっと複雑かもしれません。

絶対狼を生存させることで追加勝利になり得る役職の処置

---

server/rpc/game/game.coffee

#617 
人身御供も同じように変更しました。
（人身御供能力発動→何らかの要因で誘惑する女狼死亡→陣営変化→襲撃など・・・で
同じく能力が発動してしまうため。）

陣営変化で死亡耐性が剥がれる

---

server/rpc/game/game.coffee

e.g. DivineCursed(MikoProtected).
MikoProtected could not uncomplex as planned, if the player got DivineObstructed or DivineCursed.

fix: one-day limited skills unexpectedly prolonged

---

server/rpc/game/game.coffee

If player was fascinated by two different QueenOfNight, he would not suicide after the earlier QueenOfNight dead, because ```class Complex.beforebury()``` was overwritten.

fix: inner fascinatesuicide could not be triggered

---

server/rpc/game/game.coffee

In 一部闇鍋, if 
1. room owner excludes all jobs of 第三陣営系 other than Lorelei,
2. asks multiple 第三陣営系 jobs,
3. players number of this room is less than 13,
it will become an endless loop.

fix Endless loop related to Lorelei

---

client/code/shared/game.coffee

少人数でのプレイを想定していないため、固定禁止役職にしたく。

ローレライを隠し役職にする

---

server/rpc/game/game.coffee

公式ドキュメントより
>その夜に死亡した場合は変化しません。
役職変化中に人狼の襲撃を受けて死亡するが、ゲーム終了時に役職変化していると指摘を受けました。

課金者が死亡したときは役職変化しない

---

server/rpc/game/game.coffee

戦績表示や開始時の陣営情報ではその他だが、マニュアルが村人陣営になっていると指摘を受けたため。

盗人をその他扱いにする

---

client/code/shared/game.coffee
server/rpc/game/game.coffee

①ケミカル人狼だと鬼の占いと多分霊能結果が人間になっているので修正。
　鬼は陣営ではないので、優先度は低めに設定。（今後鬼陣営を作成するならば要検討か。）
　占い：ヴァンパイア＞人狼＞鬼
　霊能：子狐＆大狼＞人狼＞鬼
②鬼を身代わりセーフティで出現させない。
　確率で耐える＆ランダム攫いの展開はプレイヤー側は面白くないため。
③絶対狼は絆付与で死亡させる。
　後追い自殺しないという話があったため…。
　現状、絆付与は悪戯妖精しか存在しないので妖狐に対して圧倒的に人狼不利ですが…そのうち妖狐陣営以外も絆付与持ち増えるでしょうということで。

fix oni , absolutewolf

---

server/rpc/game/game.coffee

闇狼生存時は観戦者も投票結果を隠す

---

server/rpc/game/game.coffee

配信者が魔女をやってみたときに、霊界情報を開示されて荒れていたため。
配信者よりは可能性低いですが、他の変化系役職も同様に生存中禁止にさせます。
（該当役職：人狼占い、課金者、運命の子、配信者）
コピーやドッペルゲンガー、フランケンシュタインの怪物については、蘇生役職が存在しないとこの事例は起こらないため問題ないです。

一部の役職を霊界表示なしにさせる

---

server/rpc/game/game.coffee

人狼の襲撃と同時に蘇生された例が出たため。
midnightsortで人狼の襲撃よりも後に設置しておけば問題ないと思っていました、すみません。

御子が死亡したときは蘇生をキャンセルする

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/196227
課金者の投票数の減少が血狼や威嚇する狼の能力で継続するバグ修正

fix SpentVotesForGacha

---

server/rpc/game/game.coffee

闇鍋セーフティの陣営調整したまま2陣営戦ありにするとそれなりの確率で村人が出現する不具合の修正です。
陣営数調整すると、possibilityの数が強制的に0になってしまうため村人が配役されていました。すみません。
例外的に2陣営戦ありの場合>addTeamToExceptions "Human"を外して残りは村人陣営を出現させるようにします。

2陣営戦で除外しても村人が出現してしまう

---

server/rpc/game/game.coffee

ケミカル人狼で月下美人・直感派狼・月狼が右側にあるときに護衛されても能力がはたらかない不具合の修正です。
直近PR送った遺品整理士についてもケミカル用の処理をこちらで加えておきます。

護衛されたときに能力がはたらかない in Chemical

---

server/rpc/game/game.coffee

通訳の能力によって共有者など元々使える役職にこのサブ役職を付与した際に、二重三重に会話の種類が増えていくのをやめる。
元のComplexから持っていきましたが、上手い感じに書けなかったのでこれでおかしかったら修正お願いします。

会話の追加をそのまま連結させない

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/200687
猶予時間を過ぎ、未投票で突然死した場合蘇生した側も連鎖的に突然死してしまう。
赤ずきんのようにbeforeburyで処理させた場合は恐らく大丈夫だと思われますが、確かめるのも面倒なのでハンターのように能力は発動させないように変更します。

転生者が突然死した場合は蘇生させない

---

server/rpc/game/game.coffee

fix #754
少し考えましたが、良さげな案がないので、
素直にsacrificeが死因のときは処理をキャンセルする方向にしておきます。
ただし、今後何らかの死を他者に押し付けるシステムが出てきた際に、再度この問題に直面します。

fix SacrificeProtected

---

server/rpc/game/game.coffee

陣営も変更するこの役職は特に低人数時に大きく影響を与えていそうなのでとりあえず陣営数調整に入れました。
この生存役職を生む役職は不評ですね。

陣営数調整に決闘者を追加する

---

server/rpc/game/game.coffee

転生者が複数居る場合、人狼陣営が著しく不利になるため。
若しくは、1度だけの能力に調整しても良いかもしれません。
https://jinrou.uhyohyo.net/room/202325
例は転生者*2、フランケンシュタインの怪物が偶然出た村

転生者は他の転生者を蘇生させない

---

README.mediawiki
package-lock.json
package.json
server/db.coffee
server/libs/userlogs.coffee
server/rpc/game/rooms.coffee
server/rpc/user.coffee

I updated my mongodb to 6.0 last weekend(limited by my ubuntu 18.04 server), the storage shrinks to 7.5GB form 33GB after I changed Engine from `MMAPv1` to `WiredTiger`, and I can connect to it using Mongo Compass now.
It's a painful path, but I think it worth.
Recommended.

Update mongodb dependency for MongoDB 6.0+
