uhyo/jinrou

server/rpc/game/game.coffee

Error occurs when target was BombTrapped

Dictator bug fix

---

server/rpc/game/game.coffee

Blasphemy bug fix

---

server/rpc/game/game.coffee

gone-night

---

server/rpc/game/game.coffee

Error occurs on Hoodlum created by WolfDiviner
@flag is null

Hoodlum bug fix

---

server/rpc/game/game.coffee

It should be “type” here, or it will cause error as type is undefined.

WolfMinion Jobinfo Bug Fix

---

server/rpc/game/game.coffee

Didn't start cron.CronJob
https://github.com/ncb000gt/node-cron/#usage-basic-cron-usage

Fix CronJob

---

server/rpc/game/game.coffee

TypeError: Object #<Chemical> has no method 'isAttacker', which is called by line4988, code at class SolitudeWolf.

Chemical bug fix

---

server/rpc/game/game.coffee

Jobs like Mad Dog, created by Wolf Diviner, could use their night skill during the first night.
```
#MadDog
sunset:(game)->
if @flag || game.day==1
@setTarget ""
else
@setTarget null
jobdone:(game)->@target? || @flag
```

WolfDiviner Bug Fix

---

server/rpc/game/game.coffee

ToughGuy bug fix #25

---

server/rpc/game/game.coffee

1. Fireworks should be lit at just the moment before sunset, instead of immediately.
2. Dead players like BloodyMary also need ```@uncomplex()``` from WatchingFireworks.
ps: It seems I should just restore the last commit, not to remove the remote branch and then republish it.
Very sorry for disturbing you.

Pyrotechnist bug fix

---

server/rpc/game/game.coffee

my server crashed for missing these “?” Q_Q

server crash

---

client/code/app/app.coffee
client/code/app/index.coffee
client/code/pages/reset.coffee
client/code/pages/user/profile.coffee
client/templates/reset.jade
client/templates/top.jade
client/templates/user/profile.jade
config.default/app.coffee
package.json
server/mailer.coffee
server/prize.coffee
server/rpc/user.coffee

Some players have recently contacted me because they forgot their passwords. So I developed this feature to make it easy for reseting password.
I choose nodemailer v2.7.2 because it is MIT. 
Need to set a mail account in ```/config/app.coffee``` for sending emails.
Need to run ```npm install``` for nodemailer.

Mail verification system

---

server/rpc/game/game.coffee

https://twitter.com/Sunev_C/status/838045987805388801

FrankensteinsMonster will never eat each other

---

server/mailer.coffee

TypeError: Cannot set property 'from' of null
at /home/werewolf/jinrou/server/mailer.coffee:51:13

TypeError: Cannot set property 'from' of null

---

server/rpc/game/game.coffee

ReferenceError: subt is not defined
at Chemical.isWinner

spell mistake

---

app.js
server/db.coffee

this should avoid a lot of ```ReferenceError: M is not defined``` while restarting.

start server.listen after DB connected

---

client/code/shared/game.coffee

isYaminabe

---

server/rpc/game/game.coffee

A rare bug that a MadWolf could kill at some time because [this](https://github.com/uhyo/jinrou/blob/master/server/rpc/game/game.coffee#L2528)

MadWolf scapegoat bug

---

server/rpc/game/rooms.coffee

user name must not only be space

---

server/rpc/game/game.coffee

The draw caused by Miko's GONE is pretty annoying.
I guess you have the same idea.

miko-gone punish

---

server/oauth.coffee
server/rpc/game/game.coffee

#157 
and by the way, ```err.toString()``` is not ```"[object Object]"```, so I use ```err.length``` to make sure wether ```err``` is an Array

include @rule.friendssplit

---

package-lock.json
server/rpc/game/game.coffee

Scapegoat vote

---

server/rpc/game/game.coffee

The transforming log of Cursed comes twice

---

server/rpc/game/game.coffee

sleeping scapegoat should not attack

---

language/ja/game.yaml
language/ja/roles.yaml
server/rpc/game/game.coffee

By setting ```log.to``` as -1, these logs will be invisible until game end.

Show some invisible detail for easy analysis.

---

server/rpc/game/game.coffee

https://twitter.com/hakoniwawind/status/1058346783993036802
>http://werewolf.mo61.mobi/rule.html
銃殺タイミングを考えると、ハンター（復讐人）についても削除。

Only midnight can be touched

---

server/rpc/game/game.coffee

転生対象から身代わりくんを除外

---

.gitignore
client/code/pages/game/game.coffee
client/code/pages/game/newroom.coffee
client/templates/game/newroom.jade
front/src/pages/game-view/defs/room.ts
front/src/pages/game-view/room-controls/index.tsx
language/ja/game.yaml
language/ja/rooms.yaml
server/rpc/game/game.coffee
server/rpc/game/rooms.coffee
server/rpc/game/themes.coffee
server/themes/example.coffee
server/themes/readme.md

use built-in identity in blind room

---

server/rpc/game/game.coffee

Idol cannot figure out a Fan who died and reincarnated in mode of EndlessYaminabe

FanOfIdol may reincarnate and get rid of Idol

---

server/rpc/game/game.coffee

#443
あと、警備員がサイコだと死ななかったので暴徒もif文から抜けておきます。

暴徒関連もサイコに触れる

---

client/code/shared/game.coffee
server/rpc/game/game.coffee

and scapegoat should not join as HooliganGuard or HooliganAttacker

player should not rebirth into HooliganGuard and HooliganAttacker

---

server/rpc/game/game.coffee

設定されていなかったので。数値は勝手に設定してしまっていますが…。
帰省者　商人の弱体化　商人(18) - 2 = 16
奇術師　魔女≦奇術師＜デスノートと考えて、23 <= x < 30 ・・・x = 25くらいに。

jobStrength

---

server/rpc/game/game.coffee

初日白通知ありで仙狐が溶ける

---

server/rpc/game/game.coffee

https://twitter.com/makaron_lift/status/1073553836059504641
1縄分増やすという意味で10→12へ。
jingais 基本処理内では10～12で人狼系には手を出していないため、背反は無いと考えています。
ご査収ください。

人狼系ランダム調整fix

---

server/rpc/game/game.coffee

hidden log

---

server/rpc/game/game.coffee

盗まれても元々村人でなければ女王は見えない

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/141418
黒い村で狼少年が全く機能していないため。
自由配役時も考えて闇鍋以外でも適用するようにif文の外へまるごと移動。

DIVINER_NOIMMEDIATE_JOBS を闇鍋以外でも適用する

---

language/ja/game_client.yaml

fix info of peers

---

server/rpc/game/rooms.coffee

This is to prevent player joining game with name which looks to same with others.

replace invisible characters from name while joing game

---

server/rpc/game/game.coffee

fix reviveWrongPlayer

---

front/src/pages/new-room/component.tsx

savedRule.number→savedRule.maxnumber

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/142895
>選択した人が行動可能かどうかは、その人にその夜何らかの選択肢が表示されたかどうかで判断されます。
上記のように公式ドキュメントで書かれていて、忍者の結果が「行動なし」になるのは正常な動作なのですが、人狼は動く判定になるため、占い師も例外として動くように判定を変更したく。

初日白通知ありの占い師は動く

---

server/rpc/game/game.coffee

ついでに、役職調整時に占い系が居なければ出現しない枠に追加。

サトリも占い結果がすぐ分かる

---

server/rpc/game/game.coffee

Sunev/jinrou#87
``````
pl.setFlag ""
``````
cannot reset CraftyWolf's flag.

fix CraftyWolf's unexpected reviving

---

server/rpc/game/game.coffee

As he might be attacked by a Werewolf×Vampire using Vampire's skill.
related Sunev/jinrou#95

TrapGuarded should set trap according to the found instead of attacker's job.

---

server/rpc/game/game.coffee

Cat should not revive dead player not yet found

---

client/code/pages/game/game.coffee
front/package-lock.json
front/src/init-icons.ts
front/src/pages/room-list/defs.ts
front/src/pages/room-list/elements.tsx
front/src/pages/room-list/room.tsx
language/ja/game_client.yaml
server/rpc/game/rooms.coffee
server/rpc/game/themes.coffee

give icon of theater-masks to rooms with theme

---

server/rpc/game/game.coffee

歌人もサイコに関わると死ぬ

---

server/rpc/game/game.coffee

https://github.com/Sunev/jinrou/issues/106

天邪鬼の勝利判定は陣営依存

---

language/ja/game.yaml
server/rpc/game/game.coffee

https://twitter.com/nuttuttu2/status/1152623654716358657
敗北村から唐突に普通村になったりすることもあり、どちらかと言えば欲しいので勝手に作成しました。

敗北村の場合、スタート時に公開する

---

server/rpc/game/game.coffee

怪盗が二重人格を盗んだ場合、その日は陣営なしになる

---

server/rpc/user.coffee

Users are confused about receiving confirmation emails after entering the wrong password.
Although I think this is unnecessary, let's add this authorization check.

Security: add auth check when confirming/changing a mail address

---

config.default/app.coffee
package-lock.json
package.json
server/oauth.coffee

Make twitter things optional and introduce weibo

Introduce weibo

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/172728

総人狼数と絶対狼数が一致してしまうことがある

---

server/rpc/game/game.coffee

Pyrotechnist×Pyrotechnist fails at some time.
Remove Player.accessByJobType() as which is not used any more.

fix Pyrotechnist

---

server/rpc/game/game.coffee

夢遊病者の徘徊ログが人狼の人数分表示されてしまうので一回にまとめました。

fix Sleepwalker

---

language/ja/game.yaml

https://github.com/Sunev/jinrou/issues/138

fix founddetail

---

server/rpc/game/game.coffee

https://jinrou.uhyohyo.net/room/196595
仙狐が死亡時に透視した結果が蘇生後に表示されてしまうバグの修正

fix XianFox

---

server/rpc/game/game.coffee

ケミカル人狼で金鬼が条件達成しても常に敗北扱いとなる不具合の修正です。

金鬼が条件達成しても敗北する

---

server/rpc/game/game.coffee

セーフティ低以上だとローレライが出現しない不具合の修正です。

ローレライが出現しない

---

server/rpc/game/game.coffee

prevent to rebirth immediately

---

server/rpc/game/rooms.coffee

ゲームマスター:
GM蹴ろうとしたら【common.kick.noKickGM】ってでてダメでした

fix nokickGM

---

client/code/shared/game.coffee

量子人狼でサブ役職を無効にします。
https://jinrou.uhyohyo.net/room/203376
https://jinrou.uhyohyo.net/room/203378

サブ役職を許可しない in 量子

---

server/rpc/game/game.coffee

fix AttractiveWoman

---

server/rpc/game/game.coffee

fix StraySheep

---

server/rpc/game/game.coffee

fix RaidProtected

---

server/rpc/game/game.coffee

fix RaidProtected2

---

language/ja/game_client_form.yaml
language/ja/roles.yaml

Use blank lines to separate frequently-changing content from infrequently-changing content, which would reduce the work in my Merge&Translation process.

add blank line to some .yaml files

---

server/rpc/game/game.coffee

fix #796
送ったあと思いましたが、
蘇生等を考えると、deadnightで上書きよりも、midnightの動きを呼び出したほうが良かったかもしれません。
久々すぎて頭が回っていません。。

fix DarkPsychic
